<?php

// autoload.php @generated by Composer

/**
 * 此文件放置于 vendor/ 目录下
 */

require_once __DIR__ . '/composer/autoload_real.php';

//数据库微框架
require 'Medoo/Medoo.php';
//配置文件常量
require 'config/params.php';
require 'config/msg.php';
require 'config/database_info.php';


//类自动加载器
spl_autoload_register(function ($classname) {
    //路径转义
    $classname = str_replace('\\',"/",$classname);
    $classname = $classname.'.php';
    if(file_exists($classname)){
        require $classname;
    }else{
        die("unable to autoload Class $classname");
    }
});

return ComposerAutoloaderInita5622834132668ba4f01374cb8812a41::getLoader();
